### ISSUE TITLE
No “featureemb” in Config.json

### ISSUE THREAD

**Issue by jevonxu** [ermongroup/CSDI#1]
**Thanks for your sharing and I tried the exe_physio.py in the "pretrained" mode， it had following error：**

  File "D:\Code\CSDI\CSDI-main\main_model.py", line 14, in __init__
    self.emb_feature_dim = config["model"]["featureemb"]

KeyError: 'featureemb'

**Comment by y-tashi** [comment]
Thank you for letting me know.
I forgot to rename it in the config file. I've fixed it.
