### ISSUE TITLE
Time series Forecasting example with test pattern strategy 

### ISSUE THREAD

**Issue by shumatsu123** [ermongroup/CSDI#6]
Hello, thank you for your excellent work.
I would like to try time series forecasting using the test pattern strategy described in the paper. 
Are there any the example code on github?

**Comment by y-tashi** [comment]
Hi, sorry for the late reply.
I have updated the repo for time series forecasting. Please see the new codes.

**Comment by shumatsu123** [comment]
Thank you! This will help me.
