### ISSUE TITLE
difference between deterministic imputation and interpolation

### ISSUE THREAD

**Issue by JeremyChou28** [ermongroup/CSDI#7]
I’m very interested in your work. But I have a question about the difference between deterministic imputation and interpolation. 
1. May I ask why you want to do the deterministic imputation and interpolation experiments separately? I feel like they both impute the missing values. 
2. Apart from the different data, are there any differences in the tasks between the two experiments?
Looking forward to your reply, thanks.

**Comment by y-tashi** [comment]
Hi, sorry for the late reply. 
we followed the experiment settings in previous studies. Technically, there is no difference between interpolation and imputation in our paper.
