### ISSUE TITLE
testing time 

### ISSUE THREAD

**Issue by xchuwenbo** [ermongroup/CSDI#8]
I ran the code you posted on github and found that the time of training for a epoch takes about half a minute but the testing takes about half a hour(The command is “python exe_physio.py --testmissingratio 0.1 --nsample 100”). May I ask if this is in line with the actual situation.

**Comment by y-tashi** [comment]
Hi, sorry for the late reply.
Yes, it's working correctly.
Our code is not fast at test time. To accelerate the speed, You can combine CSDI with methods which speed up diffusion models.

**Comment by xchuwenbo** [comment]
Hi, Tashiro,

Thanks for your reply. We have already finished the comparison experiment and report as it was described in the paper. 

Wenbo

tldr: our recent work is deep ensembles method combined with quantile regression. it is faster than the generative models, such as the diffusion models. 
Deep Ensembles Meets Quantile Regression: Uncertainty-aware Imputation for Time Series.
Ying Liu+, Peng Cui+, Wenbo Hu, Richang Hong
https://arxiv.org/abs/2312.01294
