### ISSUE TITLE
square root for the second coefficient

### ISSUE THREAD

**Issue by willtryagain** [ermongroup/CSDI#9]
Hi, 

In [this](https://github.com/ermongroup/CSDI/blob/main/main_model.py#L122) line, to generate noisy data, why is the square root of $1 - \alpha_t$ being taken?

The paper did not have a square root for the second coefficient.

**Comment by y-tashi** [comment]
Hi, sorry for the late reply.
The paper contains typos. The code is correct.
Please also refer to the DDPM paper.
